language: go
sudo: required
dist: xenial
go:
  - "1.11"
  - "1.12"
  - "1.13"
  - tip
os:
  - linux
  - osx
  - windows
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
script:
  - go test -v -cover
  - docker build .
