version: "2"

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ${PWD}:/go/src/gitlab.com/pantacor/pantahub-base
    env_file: ./.env.local
    ports:
      - 12365:12365
    depends_on:
      - mongo
      - fluentd
      - kafka
      - elasticsearch

  fluentd:
    image: fluent/fluentd

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always

  mongo:
    image: mongo
    volumes:
      - ./mongo-entrypoint.sh:/docker-entrypoint
    command: /docker-entrypoint

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:5.0.1
    volumes:
      - ./kafka-entrypoint.sh:/docker-entrypoint
    command: /docker-entrypoint
    links:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_BROKER_ID=2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
