services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
      - fluentd
      - elasticsearch
      - localstack
    ports:
      - 12365:12365
    volumes:
      - ${PWD}/.env.local:/opt/ph/bin/env.default

  mongo:
    image: mongo
    volumes:
      - ./pantahub-base-mongo-docker-run:/docker-entrypoint
    command: /docker-entrypoint

  fluentd:
    image: fluent/fluentd:v1.16-debian

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always

  localstack:
    image: localstack/localstack:0.9.0
    environment:
      - SERVICES=s3:4566
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=localstack
    ports:
      - "4566:4566"
