version: "3"

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.development
    links:
      - mongo
      - fluentd
      - elasticsearch
      - localstack
    volumes:
      - ${PWD}:/go/src/gitlab.com/pantacor/pantahub-base
    ports:
      - 12365:12365
    env_file:
      - ./env.default 
      - ./.env.local

  mongo:
    image: mongo
    volumes:
      - ./pantahub-base-mongo-docker-run:/docker-entrypoint
    command: /docker-entrypoint

  fluentd:
    image: fluent/fluentd

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always

  localstack:
    image: localstack/localstack:0.9.0
    environment:
      - SERVICES=s3:5000
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=localstack
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker_confs/nginx-conf.d:/etc/nginx/conf.d:ro
      - ./docker_confs/nginx-certs.d/:/etc/nginx/certs.d:ro
    ports:
      - "12375:80"
      - "12376:443"
    links:
      - base
