#!/bin/sh

set -x

mongod --bind_ip_all --port 27017 &

sleep 10

mongo --eval "db.createUser({user:"user",pwd:"pass",roles:[{role:"readWrite",db:"testdb-pantabase-serv"}]})"

tail -f /proc/$(pidof mongod)/fd/1
