/* 
 * PANTAHUB Core API - Trails
 *
 * Join the Federation of Humans and Things, with cloud and devices
 *
 * OpenAPI spec version: 1.0.0
 * Contact: asac129@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type Step struct {

	// prn resource id for the owner of this trail. identical to id in trail
	Owner string `json:"owner,omitempty"`

	// prn resource id for the device of this trail
	Device string `json:"device,omitempty"`

	// prn resource id of the account that has posted the step
	Committer string `json:"committer,omitempty"`

	// object id of the parent trail
	TrailId string `json:"trail-id,omitempty"`

	// The devision of the step
	Rev float32 `json:"rev,omitempty"`

	// commit message - human readable short description of the change done by going this step
	CommitMsg string `json:"commit-msg,omitempty"`

	// the json state goal of the step
	State Object `json:"state,omitempty"`
}
