package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*UserLoginResponse user login response

swagger:model UserLoginResponse
*/
type UserLoginResponse struct {

	/* the access token for the login
	 */
	Token string `json:"token,omitempty"`
}

// Validate validates this user login response
func (m *UserLoginResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
