package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*UserLogin user login

swagger:model UserLogin
*/
type UserLogin struct {

	/* login-id of the user to log in
	 */
	LoginID string `json:"login-id,omitempty"`

	/* the secret of the login-id
	 */
	Secret string `json:"secret,omitempty"`
}

// Validate validates this user login
func (m *UserLogin) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
