package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"pantahub-base/auth/swagger/models"
)

// GetAuthLoginReader is a Reader for the GetAuthLogin structure.
type GetAuthLoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetAuthLoginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAuthLoginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetAuthLoginDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetAuthLoginOK creates a GetAuthLoginOK with default headers values
func NewGetAuthLoginOK() *GetAuthLoginOK {
	return &GetAuthLoginOK{}
}

/*GetAuthLoginOK handles this case with default header values.

The Login Response
*/
type GetAuthLoginOK struct {
	Payload *models.UserLoginResponse
}

func (o *GetAuthLoginOK) Error() string {
	return fmt.Sprintf("[GET /auth/login][%d] getAuthLoginOK  %+v", 200, o.Payload)
}

func (o *GetAuthLoginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserLoginResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuthLoginDefault creates a GetAuthLoginDefault with default headers values
func NewGetAuthLoginDefault(code int) *GetAuthLoginDefault {
	return &GetAuthLoginDefault{
		_statusCode: code,
	}
}

/*GetAuthLoginDefault handles this case with default header values.

Unexpected error
*/
type GetAuthLoginDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get auth login default response
func (o *GetAuthLoginDefault) Code() int {
	return o._statusCode
}

func (o *GetAuthLoginDefault) Error() string {
	return fmt.Sprintf("[GET /auth/login][%d] GetAuthLogin default  %+v", o._statusCode, o.Payload)
}

func (o *GetAuthLoginDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
