package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetAuthLogin gets

get refreshed token logged in user
*/
func (a *Client) GetAuthLogin(params *GetAuthLoginParams, authInfo runtime.ClientAuthInfoWriter) (*GetAuthLoginOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAuthLoginParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetAuthLogin",
		Method:             "GET",
		PathPattern:        "/auth/login",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetAuthLoginReader{formats: a.formats},
		AuthInfo:           authInfo,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetAuthLoginOK), nil
}

/*
PostAuthLogin logs in with user credentials

login with user credentials. receive an access token for future use

*/
func (a *Client) PostAuthLogin(params *PostAuthLoginParams) (*PostAuthLoginOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostAuthLoginParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostAuthLogin",
		Method:             "POST",
		PathPattern:        "/auth/login",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostAuthLoginReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostAuthLoginOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
