package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"pantahub-base/auth/swagger/models"
)

// PostAuthLoginReader is a Reader for the PostAuthLogin structure.
type PostAuthLoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostAuthLoginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostAuthLoginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostAuthLoginDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostAuthLoginOK creates a PostAuthLoginOK with default headers values
func NewPostAuthLoginOK() *PostAuthLoginOK {
	return &PostAuthLoginOK{}
}

/*PostAuthLoginOK handles this case with default header values.

The Login Response
*/
type PostAuthLoginOK struct {
	Payload *models.UserLoginResponse
}

func (o *PostAuthLoginOK) Error() string {
	return fmt.Sprintf("[POST /auth/login][%d] postAuthLoginOK  %+v", 200, o.Payload)
}

func (o *PostAuthLoginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserLoginResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAuthLoginDefault creates a PostAuthLoginDefault with default headers values
func NewPostAuthLoginDefault(code int) *PostAuthLoginDefault {
	return &PostAuthLoginDefault{
		_statusCode: code,
	}
}

/*PostAuthLoginDefault handles this case with default header values.

Unexpected error
*/
type PostAuthLoginDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post auth login default response
func (o *PostAuthLoginDefault) Code() int {
	return o._statusCode
}

func (o *PostAuthLoginDefault) Error() string {
	return fmt.Sprintf("[POST /auth/login][%d] PostAuthLogin default  %+v", o._statusCode, o.Payload)
}

func (o *PostAuthLoginDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
