package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"pantahub-base/auth/swagger/models"
)

// NewPostAuthLoginParams creates a new PostAuthLoginParams object
// with the default values initialized.
func NewPostAuthLoginParams() *PostAuthLoginParams {
	var ()
	return &PostAuthLoginParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAuthLoginParamsWithTimeout creates a new PostAuthLoginParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAuthLoginParamsWithTimeout(timeout time.Duration) *PostAuthLoginParams {
	var ()
	return &PostAuthLoginParams{

		timeout: timeout,
	}
}

/*PostAuthLoginParams contains all the parameters to send to the API endpoint
for the post auth login operation typically these are written to a http.Request
*/
type PostAuthLoginParams struct {

	/*Userlogin*/
	Userlogin *models.UserLogin

	timeout time.Duration
}

// WithUserlogin adds the userlogin to the post auth login params
func (o *PostAuthLoginParams) WithUserlogin(userlogin *models.UserLogin) *PostAuthLoginParams {
	o.Userlogin = userlogin
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Userlogin == nil {
		o.Userlogin = new(models.UserLogin)
	}

	if err := r.SetBodyParam(o.Userlogin); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
