package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"pantahub-base/auth/swagger/client/operations"
)

// Default a b c i e core API identity and auth HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new a b c i e core API identity and auth HTTP client.
func NewHTTPClient(formats strfmt.Registry) *PANTAHUBCoreAPIIdentityAndAuth {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("api.pantahub.com", "/api", []string{"https", "http"})
	return New(transport, formats)
}

// New creates a new a b c i e core API identity and auth client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *PANTAHUBCoreAPIIdentityAndAuth {
	cli := new(PANTAHUBCoreAPIIdentityAndAuth)
	cli.Transport = transport

	cli.Operations = operations.New(transport, formats)

	return cli
}

// PANTAHUBCoreAPIIdentityAndAuth is a client for a b c i e core API identity and auth
type PANTAHUBCoreAPIIdentityAndAuth struct {
	Operations *operations.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *PANTAHUBCoreAPIIdentityAndAuth) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Operations.SetTransport(transport)

}
