package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"pantahub-base/devices/swagger/models"
)

// GetDevicesReader is a Reader for the GetDevices structure.
type GetDevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetDevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetDevicesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetDevicesOK creates a GetDevicesOK with default headers values
func NewGetDevicesOK() *GetDevicesOK {
	return &GetDevicesOK{}
}

/*GetDevicesOK handles this case with default header values.

The Objects in the store
*/
type GetDevicesOK struct {
	Payload []*models.Device
}

func (o *GetDevicesOK) Error() string {
	return fmt.Sprintf("[GET /devices/][%d] getDevicesOK  %+v", 200, o.Payload)
}

func (o *GetDevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDevicesDefault creates a GetDevicesDefault with default headers values
func NewGetDevicesDefault(code int) *GetDevicesDefault {
	return &GetDevicesDefault{
		_statusCode: code,
	}
}

/*GetDevicesDefault handles this case with default header values.

Unexpected error
*/
type GetDevicesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get devices default response
func (o *GetDevicesDefault) Code() int {
	return o._statusCode
}

func (o *GetDevicesDefault) Error() string {
	return fmt.Sprintf("[GET /devices/][%d] GetDevices default  %+v", o._statusCode, o.Payload)
}

func (o *GetDevicesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
