package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"pantahub-base/devices/swagger/models"
)

// GetDevicesDeviceIDReader is a Reader for the GetDevicesDeviceID structure.
type GetDevicesDeviceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetDevicesDeviceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDevicesDeviceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetDevicesDeviceIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetDevicesDeviceIDOK creates a GetDevicesDeviceIDOK with default headers values
func NewGetDevicesDeviceIDOK() *GetDevicesDeviceIDOK {
	return &GetDevicesDeviceIDOK{}
}

/*GetDevicesDeviceIDOK handles this case with default header values.

The Device found
*/
type GetDevicesDeviceIDOK struct {
	Payload *models.Device
}

func (o *GetDevicesDeviceIDOK) Error() string {
	return fmt.Sprintf("[GET /devices/{device-id}][%d] getDevicesDeviceIdOK  %+v", 200, o.Payload)
}

func (o *GetDevicesDeviceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Device)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDevicesDeviceIDDefault creates a GetDevicesDeviceIDDefault with default headers values
func NewGetDevicesDeviceIDDefault(code int) *GetDevicesDeviceIDDefault {
	return &GetDevicesDeviceIDDefault{
		_statusCode: code,
	}
}

/*GetDevicesDeviceIDDefault handles this case with default header values.

Unexpected Error
*/
type GetDevicesDeviceIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get devices device ID default response
func (o *GetDevicesDeviceIDDefault) Code() int {
	return o._statusCode
}

func (o *GetDevicesDeviceIDDefault) Error() string {
	return fmt.Sprintf("[GET /devices/{device-id}][%d] GetDevicesDeviceID default  %+v", o._statusCode, o.Payload)
}

func (o *GetDevicesDeviceIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
