package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"pantahub-base/devices/swagger/models"
)

// NewPostDevicesParams creates a new PostDevicesParams object
// with the default values initialized.
func NewPostDevicesParams() *PostDevicesParams {
	var ()
	return &PostDevicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDevicesParamsWithTimeout creates a new PostDevicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDevicesParamsWithTimeout(timeout time.Duration) *PostDevicesParams {
	var ()
	return &PostDevicesParams{

		timeout: timeout,
	}
}

/*PostDevicesParams contains all the parameters to send to the API endpoint
for the post devices operation typically these are written to a http.Request
*/
type PostDevicesParams struct {

	/*Newobject*/
	Newobject *models.Device

	timeout time.Duration
}

// WithNewobject adds the newobject to the post devices params
func (o *PostDevicesParams) WithNewobject(newobject *models.Device) *PostDevicesParams {
	o.Newobject = newobject
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostDevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Newobject == nil {
		o.Newobject = new(models.Device)
	}

	if err := r.SetBodyParam(o.Newobject); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
