package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Device device

swagger:model Device
*/
type Device struct {

	/* id of the object
	 */
	ID string `json:"id,omitempty"`

	/* the prn id of the owner for the device
	 */
	Owner string `json:"owner,omitempty"`

	/* the device auth secret used by the ID provider
	 */
	Secret string `json:"secret,omitempty"`
}

// Validate validates this device
func (m *Device) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
