//
// Copyright (c) 2017-2026 Pantacor Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

package base

import (
	"context"
	"encoding/base64"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"
	"time"

	jwtgo "github.com/golang-jwt/jwt/v5"
	"github.com/rs/cors"
	httpSwagger "github.com/swaggo/http-swagger"
	"gitlab.com/pantacor/pantahub-base/apps"
	"gitlab.com/pantacor/pantahub-base/auth"
	"gitlab.com/pantacor/pantahub-base/auth/authservices"
	"gitlab.com/pantacor/pantahub-base/callbacks"
	"gitlab.com/pantacor/pantahub-base/changes"
	"gitlab.com/pantacor/pantahub-base/cron"
	"gitlab.com/pantacor/pantahub-base/dash"
	"gitlab.com/pantacor/pantahub-base/devices"
	"gitlab.com/pantacor/pantahub-base/exports"
	"gitlab.com/pantacor/pantahub-base/healthz"
	"gitlab.com/pantacor/pantahub-base/logs"
	"gitlab.com/pantacor/pantahub-base/mcp"
	"gitlab.com/pantacor/pantahub-base/metrics"
	"gitlab.com/pantacor/pantahub-base/mqtt"
	"gitlab.com/pantacor/pantahub-base/objects"
	"gitlab.com/pantacor/pantahub-base/plog"
	"gitlab.com/pantacor/pantahub-base/profiles"
	"gitlab.com/pantacor/pantahub-base/subscriptions"
	"gitlab.com/pantacor/pantahub-base/tokens"
	"gitlab.com/pantacor/pantahub-base/trails"
	"gitlab.com/pantacor/pantahub-base/utils"
	"gitlab.com/pantacor/pantahub-base/utils/echoutil"
	"gitlab.com/pantacor/pantahub-base/utils/jwtauth"
	"gitlab.com/pantacor/pantahub-base/webhooks"

	_ "gitlab.com/pantacor/pantahub-base/docs" // docs is generated by Swag CLI, you have to import it.
)

// DoInit init pantahub REST Application
func DoInit() http.Handler {
	mux := http.NewServeMux()

	// Global echo server; services move onto it one mux prefix at a time.
	echoServer := echoutil.NewServer(os.Getenv("OTEL_SERVICE_NAME"))

	// GET /features — active optional features, for the UI to cache and gate on
	mux.HandleFunc("/features", featuresHandler)
	mux.HandleFunc("/features/", featuresHandler)

	if err := LoadDynamicS3ByRegion(); err != nil {
		panic(err)
	}

	phAuth := utils.GetEnv(utils.EnvPantahubAuth)
	jwtSecretBase64 := utils.GetEnv(utils.EnvPantahubJWTAuthSecret)
	jwtSecretPem, err := base64.StdEncoding.DecodeString(jwtSecretBase64)
	if err != nil {
		panic(fmt.Errorf("no valid JWT secret (PANTAHUB_JWT_SECRET) in base64 format: %s", err.Error()))
	}
	jwtSecret, err := jwtgo.ParseRSAPrivateKeyFromPEM(jwtSecretPem)
	if err != nil {
		panic(fmt.Errorf("no valid JWT secret (PANTAHUB_JWT_SECRET); must be rsa private key in PEM format: %s", err.Error()))
	}

	jwtPubBase64 := utils.GetEnv(utils.EnvPantahubJWTAuthPub)
	jwtPubPem, err := base64.StdEncoding.DecodeString(jwtPubBase64)
	if err != nil {
		panic(fmt.Errorf("no valid JWT PUB KEY (PANTAHUB_JWT_PUB) in base64 format: %s", err.Error()))
	}
	jwtPub, err := jwtgo.ParseRSAPublicKeyFromPEM(jwtPubPem)
	if err != nil {
		panic(fmt.Errorf("no valid JWT pub key (PANTAHUB_JWT_PUB); must be rsa private key in PEM format: %s", err.Error()))
	}

	mongoClient, _ := utils.GetMongoClient()

	timeoutStr := utils.GetEnv(utils.EnvPantahubJWTTimeoutMinutes)
	timeout, err := strconv.Atoi(timeoutStr)
	if err != nil {
		panic(err)
	}

	maxRefreshStr := utils.GetEnv(utils.EnvPantahubJWTMaxRefreshMinutes)
	maxRefresh, err := strconv.Atoi(maxRefreshStr)
	if err != nil {
		panic(err)
	}

	jwtConfig := &jwtauth.Config{
		Key:              jwtSecret,
		Pub:              jwtPub,
		Realm:            "\"pantahub services\", ph-aeps=\"" + phAuth + "\"",
		Authenticator:    falseAuthenticator,
		Timeout:          time.Minute * time.Duration(timeout),
		MaxRefresh:       time.Minute * time.Duration(maxRefresh),
		SigningAlgorithm: "RS256",
	}
	jwtConfig.Authenticator = authservices.AuthWithUserPassFactory(mongoClient)
	jwtConfig.PayloadFunc = authservices.AuthenticatePayloadFactory(mongoClient, jwtConfig)

	utils.BasicAuthTokenFactory = authservices.CreateBearerFromPersonalToken

	adminUsers := utils.GetSubscriptionAdmins()
	subService := subscriptions.NewService(mongoClient, utils.Prn("prn::subscriptions:"),
		adminUsers, subscriptions.SubscriptionProperties)

	// Kept in scope for the MCP endpoint below, which registers itself as a
	// resource this authorization server may bind tokens to.
	// auth gets its own config: New installs its Authenticator/PayloadFunc.
	authApp := auth.New(&jwtauth.Config{
		Key:              jwtSecret,
		Pub:              jwtPub,
		Realm:            "\"pantahub services\", ph-aeps=\"" + phAuth + "\"",
		Timeout:          time.Minute * time.Duration(timeout),
		MaxRefresh:       time.Minute * time.Duration(maxRefresh),
		SigningAlgorithm: "RS256",
	}, mongoClient)
	{
		authApp.Mount(echoServer)
		mux.Handle("/auth/", echoServer.E) // echo

		// RFC 8414 discovery: how an OAuth client that only knows this API's
		// URL finds the authorize and token endpoints under /auth/oauth.
		for _, path := range auth.AuthorizationServerMetadataPaths() {
			mux.Handle(path, authApp.AuthorizationServerMetadataHandler())
		}
	}
	{
		app := objects.New(jwtConfig, subService, mongoClient)
		app.Mount(echoServer)
		mux.Handle("/objects/", echoServer.E) // echo
	}
	{
		app := changes.New(jwtConfig, mongoClient)
		app.Mount(echoServer)
		mux.Handle("/changes/", echoServer.E) // echo
	}
	{
		app := devices.New(jwtConfig, subService, mongoClient)
		app.Mount(echoServer)
		mux.Handle("/devices/", echoServer.E) // echo
	}
	{
		app := trails.New(jwtConfig, mongoClient)
		app.Mount(echoServer)
		mux.Handle("/trails/", echoServer.E) // echo
	}
	{
		app := plog.New(jwtConfig, mongoClient)
		app.Mount(echoServer)
		mux.Handle("/plog/", echoServer.E) // echo
	}
	// Kept in scope for the MQTT bridge below: its backend is the only
	// registered one in this process, and an unregistered elastic backend
	// silently discards everything written through it.
	logsApp := logs.New(jwtConfig, mongoClient)
	{
		logsApp.Mount(echoServer)
		mux.Handle("/logs/", echoServer.E) // echo
	}
	{
		app := healthz.New(mongoClient)
		app.Mount(echoServer)
		mux.Handle("/healthz/", echoServer.E) // echo
	}
	{
		app := dash.New(jwtConfig, subService, mongoClient)
		app.Mount(echoServer)
		// Served by echo; routes use full paths, so no StripPrefix.
		mux.Handle("/dash/", echoServer.E)
	}
	{
		app := subscriptions.New(jwtConfig, subService, mongoClient)
		app.Mount(echoServer)
		mux.Handle("/subscriptions/", echoServer.E) // echo
	}
	{
		app := metrics.New(jwtConfig, mongoClient)
		app.Mount(echoServer)
		mux.Handle("/metrics/", echoServer.E) // echo
	}
	{
		app := apps.New(jwtConfig, mongoClient)
		app.Mount(echoServer)
		mux.Handle("/apps/", echoServer.E) // echo
	}
	{
		app := profiles.New(jwtConfig, mongoClient)
		app.Mount(echoServer)
		mux.Handle("/profiles/", echoServer.E) // echo
	}
	{
		cronJobTimeout, err := strconv.Atoi(utils.GetEnv(utils.EnvCronJobTimeout))
		if err != nil {
			panic(fmt.Errorf("error Parsing CRON_JOB_TIMEOUT: %s", err.Error()))
		}

		app := cron.New(jwtConfig, (time.Duration(cronJobTimeout) * time.Second),
			mongoClient)
		app.Mount(echoServer)
		mux.Handle("/cron/", echoServer.E) // echo
	}
	{
		app := callbacks.New(jwtConfig, mongoClient)
		app.Mount(echoServer)
		mux.Handle("/callbacks/", echoServer.E) // echo
	}
	// Kept in scope: export imports store objects through the file server
	// below, and the MCP endpoint starts uploads through it.
	anonToken := func() string { return authservices.CreateAnonToken(jwtConfig) }
	exportsApp := exports.New(jwtConfig, anonToken, mongoClient)
	exportsApp.Mount(echoServer)
	mux.Handle("/exports/", echoServer.E) // echo
	{
		app := tokens.New(jwtConfig, mongoClient)
		app.Mount(echoServer)
		mux.Handle("/tokens/", echoServer.E) // echo
	}
	if utils.FeatureEnabled(utils.EnvPantahubDisableWebhooks) {
		app := webhooks.New(jwtConfig)
		app.Mount(echoServer)
		mux.Handle("/webhooks/", echoServer.E) // echo
	} else {
		log.Println("feature disabled: webhooks (PANTAHUB_DISABLE_WEBHOOKS)")
	}

	var fservermux FileUploadServer
	switch utils.GetEnv(utils.EnvPantahubStorageDriver) {
	case "s3":
		log.Println("INFO: using 's3' driver to serve object blobs/files")
		fservermux = NewS3FileServer()
	default:
		log.Println("INFO: using 'local' driver to serve object blobs/files")
		fservermux = &LocalFileServer{fileServer: http.FileServer(http.Dir(utils.PantahubS3Path())), directory: utils.PantahubS3Path()}
	}

	// default cors - allow GET and POST from all origins
	fserver := cors.AllowAll().Handler(fservermux)

	// @deprecated
	mux.Handle("/local-s3/", http.StripPrefix("/local-s3", fserver))
	// Object signed put URLs name /local-s3/; imports use the same handler.
	exportsApp.SetObjectServer(http.StripPrefix("/local-s3", fservermux))

	// handle s3 storage request's
	mux.Handle("/s3/", http.StripPrefix("/s3", fserver))

	// The MQTT message plane shares the API's listener rather than opening a
	// port of its own: the deployment only swaps the container image, so a new
	// port would be unreachable. Devices connect to wss://<host><path>.
	if mqtt.Enabled() {
		service, err := mqtt.New(mongoClient, logsApp)
		if err != nil {
			log.Println("ERROR: could not start mqtt message plane: " + err.Error())
		} else if err := service.Start(context.Background()); err != nil {
			log.Println("ERROR: could not serve mqtt message plane: " + err.Error())
		} else {
			path := mqtt.WsPath()
			mux.Handle(path, service.Handler())
			log.Println("INFO: mqtt message plane serving at " + path)
		}
	}

	// The MCP endpoint lets an AI assistant manage the devices of the user who
	// authorized it. Like MQTT it is a plain handler on this mux rather than an
	// echo route, and it brings its own authentication.
	if mcp.Enabled() {
		service, err := mcp.New(mongoClient, logsApp)
		if err == nil {
			// Tokens for the endpoint are issued by /auth/oauth, which has to
			// know the endpoint exists and what a token for it may carry.
			err = authApp.RegisterOAuthResource(auth.OAuthResource{
				URL:           service.ResourceURL(),
				Scopes:        service.Scopes(),
				DefaultScopes: service.DefaultScopes(),
			})
		}
		if err != nil {
			log.Println("ERROR: could not start mcp endpoint: " + err.Error())
		} else {
			service.SetExportUploads(exportsApp)
			mux.Handle(mcp.Path(), service.Handler())
			for _, path := range service.MetadataPaths() {
				mux.Handle(path, service.MetadataHandler())
			}
			log.Println("INFO: mcp endpoint serving at " + mcp.Path() + " as " + service.ResourceURL())
		}
	}

	if err := echoServer.Validate(); err != nil {
		log.Fatal(err)
	}

	mux.Handle("/swagger/", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"), //The url pointing to API definition"
	))

	return mux
}
