#!/bin/sh

# Wait for Kafka to be ready
echo "Waiting for Kafka to be ready..."
if command -v cub > /dev/null; then
  cub kafka-ready -b kafka:9092 1 120
else
  until nc -z kafka 9092; do
    echo "Waiting for Kafka..."
    sleep 2
  done
fi
echo "Kafka is ready."
# Additional wait for topics
sleep 10

# Background process to upload connector configs once Kafka Connect is ready
(
  set -x
  echo "Connector Configurator: Waiting for Kafka Connect to be ready..."
  
  while true; do
    if curl -s -f http://localhost:8083 > /dev/null; then
      echo "Connector Configurator: Kafka Connect is up!"
      break
    fi
    echo "Connector Configurator: waiting for kafka connect..."
    sleep 10
  done

  echo "Connector Configurator: UPLOADING CONFIGS FOR CONNECTORS"
  for file in /opt/kafka-connect-configs/*; do
    if [ -f "$file" ]; then
      echo "Connector Configurator: Uploading $file"
      curl -X POST -H "Content-Type: application/json" -T "$file" http://localhost:8083/connectors
    fi
  done
  echo "Connector Configurator: Done."
) &

# Execute the main Kafka Connect process
exec /etc/confluent/docker/run