#!/bin/sh

set -ex

MONGO_PORT=${MONGO_PORT:-27017}

# make sure the permissions for the mongokey is correct
chmod 600 /keys/mongokey.yaml

# Background process to check replica set status (optional for secondary but good for logs)
(
  echo "Mongo Secondary: Waiting for MongoDB to start..."
  until mongo --port ${MONGO_PORT} --quiet --eval "db.adminCommand('ping')"; do
    sleep 2
  done
  echo "Mongo Secondary: MongoDB is up."
) &

# Execute mongod as main process
exec mongod --keyFile /keys/mongokey.yaml --transitionToAuth --port ${MONGO_PORT} --replSet ${MONGO_RS} --bind_ip_all "$@"