#!/bin/sh

set -e

# PREREQs on tools front

jsoncmd=`which json`

if test -z "$jsoncmd"; then
 echo "json command not found. try running 'npm install -g json'"
 exit 1
fi

if test ! -x "$jsoncmd"; then
 echo "$jsconcmd not executable? check your system..."
 exit 2
fi

httpcmd=`which http`

if test -z "$httpcmd"; then
 echo "http command not found. try installing httpie tool ..."
 exit 3
fi

if test ! -x "$httpcmd"; then
 echo "$httpcmd not executable? check your system..."
 exit 4
fi


# usage checks

usage(){
  echo "Usage: $cmd <user-prn> <user-secret> <device-prn> <rev> <state-json-file> <commit-msg>"
  if test -n "$1"; then
     echo    Error: $1
  fi
  exit 100
}

cmd=`basename $0`
user_prn="$1"
user_secret="$2"
device_prn="$3"
rev="$4"
state_jsonfile="$5"
commit_msg="$6"

if test -z "$user_prn"; then
  usage "Missing user-prn"
fi

if test -z "$user_secret"; then
  usage "Missing user-secret"
fi

if test -z "$device_prn"; then
  usage "Missing device-prn"
fi

if test -z "$rev"; then
  usage "Missing rev"
fi

if test -z "$state_jsonfile"; then
  usage "Missing state-jsonfile"
fi

if ! test -e "$state_jsonfile"; then
  usage "state-jsonfile not found: $state_jsonfile"
fi

if test -z "$commit_msg"; then
  usage "Missing commit-msg"
fi

# B U S I N E S S    L O G I C

# --- LOGIN FIRST ---

httpresult=`http POST localhost:12365/api/auth/login \
	username="$user_prn" \
	password="$user_secret"`

UTOKEN=`echo $httpresult | json token`

if test -z $UTOKEN; then
  echo "user login with given credentials ($user_prn:$user_secret) failed."
  echo Check the output below:
  echo $httpresult
  exit 100
fi


# --- MAKE THE STEP

statejson="{ \"state\": `cat $state_jsonfile | json` }"

stepjson=`echo "{ \"rev\": $rev }
{ \"commit-msg\": \"$commit_msg\" }
$statejson" | json --merge`


# --- PUSH THE STEP

trailid=`echo $device_prn | sed -e 's/.*\///'`

echo pushing step for trail: $trailid

httpresult=`echo $stepjson | json | \
	http POST localhost:12365/api/trails/$trailid/steps \
		Authorization:" Bearer $UTOKEN"`

stepid=`echo $httpresult | json id`

echo Posted step: $stepid

if test -z "$stepid"; then
  echo Error posting step. see output below:
  echo $httpresult | json
  exit 101
fi

