# go appengine

runtime: go
env: flex

env_variables:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: AKIAIR5QHQ2CEP3BQFAQ
  AWS_SECRET_ACCESS_KEY: 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
  PANTAHUB_S3PATH: production
  PANTAHUB_SCHEME: https
  PANTAHUB_HOST: api-pantahub-com.appspot.com
  PANTAHUB_PORT: ""
  PH_AUTH: https://api-pantahub-com.appspot.com/auth
  MONGO_HOST: ds145299.mlab.com
  MONGO_PORT: 45299
  MONGO_USER: api-pantahub-com-production
  MONGO_PASS: pr0dN3inT0lo
  MONGO_DB: pantabase-serv

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.9

