# go appengine

application: www-pantahub-beta
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

env_variables:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: AKIAIR5QHQ2CEP3BQFAQ
  AWS_SECRET_ACCESS_KEY: 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
  PANTAHUB_S3PATH: production
  MONGO_HOST: ds145299.mlab.com
  MONGO_PORT: 45299
  MONGO_USER: api-pantahub-com-production
  MONGO_PASS: pr0dN3inT0lo
  MONGO_DB: pantabase-serv

